services:

  db:
    image: postgres:15.6-alpine3.19
    restart: always
    container_name: cartridges-db
    healthcheck:
      test: "pg_isready -h db"
      interval: 3s
      timeout: 5s
      retries: 5
    env_file:
        - ./.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ../cartridges-database:/var/lib/postgresql/data
    ports:
      - ${DB_HOST_PORT}:${DB_PORT}

  db-postgres-setup:
    # fix permissions for postgres service
    container_name: db-postgres-setup
    image: postgres:15.6-alpine3.19
    user: root
    volumes:
        - ../cartridges-database:/var/lib/postgresql/data
    entrypoint: [ "bash", "-c", "chmod 750 -R /var/lib/postgresql/data"] 
    depends_on:
        - db

  redis:
    image: redis:latest
    container_name: cartridges-redis
    volumes:
      - ./redis/redis_data:/data
    env_file:
      - ./.env
    environment:
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: >
      sh -c '
      mkdir -p /etc/redis &&
      echo "user ${REDIS_USER} on >${REDIS_USER_PASSWORD} ~* &* +@all" > /etc/redis/users.acl &&
      chmod 644 /etc/redis/users.acl && 
      redis-server --requirepass "somepass" --aclfile /etc/redis/users.acl --appendonly yes
      '
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5