services:

  db:
    extends:
      file: docker-compose.common.yml
      service: db

  db-postgres-setup:
    extends:
      file: docker-compose.common.yml
      service: db-postgres-setup

  redis:
    ports:
      - ${REDIS_HOST_PORT}:${REDIS_PORT}
    extends:
      file: docker-compose.common.yml
      service: redis


      
  # web:
  #   extends:
  #     file: docker-compose.common.yml
  #     service: web
  #   build:
  #     context: .
  #     dockerfile: ./dockerfiles/cartridges/Dockerfile
  #   volumes:
  #     - ./.env:/code/.env