"""Remove employee and room relationship

Revision ID: 3e2b91639e1f
Revises: 7eed938ffe5f
Create Date: 2025-02-14 17:24:06.277123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2b91639e1f'
down_revision: Union[str, None] = '7eed938ffe5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cartridge', ['id'])
    op.create_unique_constraint(None, 'device', ['id'])
    op.drop_constraint('employee_room_id_fkey', 'employee', type_='foreignkey')
    op.drop_column('employee', 'room_id')
    op.create_unique_constraint(None, 'vendor', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendor', type_='unique')
    op.add_column('employee', sa.Column('room_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('employee_room_id_fkey', 'employee', 'room', ['room_id'], ['id'])
    op.drop_constraint(None, 'device', type_='unique')
    op.drop_constraint(None, 'cartridge', type_='unique')
    # ### end Alembic commands ###
