"""Emloyees personnel number null.

Revision ID: ccbe0ecf4813
Revises: e31ae0b91c2f
Create Date: 2025-09-17 21:11:07.779700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccbe0ecf4813'
down_revision: Union[str, None] = 'e31ae0b91c2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'personnel_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'personnel_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
