"""Cartridge model column

Revision ID: 5ee7811ec0cc
Revises: 89f134e16949
Create Date: 2025-09-18 17:13:40.137203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee7811ec0cc'
down_revision: Union[str, None] = '89f134e16949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartridge', sa.Column('model_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'cartridge', 'model', ['model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cartridge', type_='foreignkey')
    op.drop_column('cartridge', 'model_id')
    # ### end Alembic commands ###
