"""Cartridges, Emloyees modify.

Revision ID: e31ae0b91c2f
Revises: 3e2b91639e1f
Create Date: 2025-09-17 20:29:05.312134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e31ae0b91c2f'
down_revision: Union[str, None] = '3e2b91639e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'building', ['name'])
    op.add_column('cartridge', sa.Column('employee_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'cartridge', 'employee', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cartridge', type_='foreignkey')
    op.drop_column('cartridge', 'employee_id')
    op.drop_constraint(None, 'building', type_='unique')
    # ### end Alembic commands ###
