on: [push]

jobs:

  tests:
    name: Running pytest
    environment: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - 
      uses: actions/checkout@v4
    - 
        name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.11'
    -
      name: Install dump-env and create .env
      env:
        VARS_PROJECT_NAME: ${{ vars.PROJECT_NAME }}
        VARS_HTTP_SECURE: ${{ vars.HTTP_SECURE}}
        VARS_HTTP_PORT: ${{ vars.HTTP_PORT }}
        VARS_V1: ${{ vars.V1 }}
        VARS_HOST: ${{ vars.HOST }}
        VARS_LOG_DIR: ${{ vars.LOG_DIR }}
        VARS_ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install dump-env==1.5.0
        dump-env --template=.template.env --prefix='VARS_' \
        --prefix='SECRET_' > .env
    - 
        name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
            version: 2.0.0
            virtualenvs-create: false
            virtualenvs-in-project: false
            installer-parallel: true
    -
      name: Install dependencies
      run: poetry install --no-interaction
      # name: Setup Debug Session
      # uses: csexton/debugger-action@master
    -
      name: Tests with pytest
      run: |
        poetry run pytest
